import { ACTIVE_SCREEN_CREDIT_CARD_CARD_EROR_MESSAGE, PERSONAL_INFORMATION_DONATE_BUTTON, PERSONAL_INFORMATION_EMAIL_PLACEHOLDER, PERSONAL_INFORMATION_LAST_NAME_PLACEHOLDER, PERSONAL_INFORMATION_FIRST_NAME_PLACEHOLDER, PERSONAL_INFORMATION_SCREEN, CARD_CONTINUE_BUTTON, CREDIT_CARD_CVC_PLACEHOLDER, CREDIT_CARD_EXPIRE_DATE_PLACEHOLDER, ACTIVE_SCREEN_CREDIT_CARD, CREDIT_CARD_NUMBER_PLACEHOLDER, ACTIVE_PAYMENt_METHOD, DONATE_BUTTON, MONTHLY_BUTTON_ID, CURRENCY_BUTTON_CSS, CURRENCY_SYMBOL, AMOUNT_FILED, AMOUNT_FILED_CSS, DONATE_MONTHLY_BUTTON, COVER_TRANSACTION_COSTS_CHECKBOX, CREDIT_CARD_OPTION, CURRENCY_BUTTON_ID} from '../constants/elements';

import { test, expect } from '@playwright/test';

function clickToDonateButton(page: Page) {
    const donateButtonLocator = page
    .frameLocator('#XBGSFAMB')
    .getByTestId(DONATE_BUTTON);

  await donateButtonLocator.click();
}